name: Deploy GitHub Pages

on:
  push:
    paths:
      - 'starter-academic/public/**'
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Git
        run: |
          git config --global user.name 'ksanu1998'
          git config --global user.email 'ksanu1998@gmail.com'

      - name: Copy files
        run: |
          mkdir -p output
          cp -R starter-academic/public/* output/

      - name: Deploy to GitHub Pages
        run: |
          cd output
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin main
          git reset --hard origin/main
          git add .
          git commit -m "Deploy GitHub Pages" || exit 0
          git push --force origin main

